/*
===============================================================================
Measures Exploration - Key Business Metrics
===============================================================================
This script calculates the main business metrics from the Gold layer.

The goal is to get a quick overview of the business using aggregated values,
such as total sales, total quantity sold, average price, total orders,
products, and customers.

Main SQL concepts used:
    - SUM() to calculate totals
    - AVG() to calculate averages
    - COUNT() to count records
    - COUNT(DISTINCT) to count unique values
    - UNION ALL to combine several metrics into one report
===============================================================================
*/

-- Calculate the total revenue generated by all sales
SELECT 
    SUM(sales_amount) AS total_sales 
FROM gold.fact_sales;

-- Calculate the total number of items sold
SELECT 
    SUM(quantity) AS total_quantity 
FROM gold.fact_sales;

-- Calculate the average selling price
SELECT 
    AVG(price) AS avg_price 
FROM gold.fact_sales;

-- Count all order records in the sales table
SELECT 
    COUNT(order_number) AS total_order_rows 
FROM gold.fact_sales;

-- Count the real number of unique orders
SELECT 
    COUNT(DISTINCT order_number) AS total_orders 
FROM gold.fact_sales;

-- Count the total number of products available
SELECT 
    COUNT(product_name) AS total_products 
FROM gold.dim_products;

-- Count the total number of customers registered
SELECT 
    COUNT(customer_key) AS total_customers 
FROM gold.dim_customers;

-- Count how many unique customers have placed at least one order
SELECT 
    COUNT(DISTINCT customer_key) AS total_customers_with_orders 
FROM gold.fact_sales;

-- Create a summary report with the main business metrics
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value 
FROM gold.fact_sales

UNION ALL

SELECT 'Total Quantity', SUM(quantity) 
FROM gold.fact_sales

UNION ALL

SELECT 'Average Price', AVG(price) 
FROM gold.fact_sales

UNION ALL

SELECT 'Total Orders', COUNT(DISTINCT order_number) 
FROM gold.fact_sales

UNION ALL

SELECT 'Total Products', COUNT(DISTINCT product_name) 
FROM gold.dim_products

UNION ALL

SELECT 'Total Customers', COUNT(customer_key) 
FROM gold.dim_customers;
